export default [
    {
        id: 1,
        type: 'meal',
        title: 'Salada Ravanello',
        description: 'Rabanetes, folhas verdes e molho agridoce salpicados com gergelim.',
        img: 'mask-group.png',
        price: 49.97,
        ingredients: [
            'alface',
            'cebola',
            'pão naan',
            'pepino',
            'rabanete',
            'tomate'
        ],
        isFav: false,
    },
    {
        id: 2,
        type: 'meal',
        title: 'Torradas de Parma',
        description: 'Presunto de parma e rúcula em um pão com fermentação natural.',
        img: 'mask-group-1.png',
        price: 25.97,
        ingredients: [
            'alface',
            'cebola',
            'pão naan',
            'pepino',
            'rabanete',
            'tomate'
        ],
        isFav: false,
    },
    {
        id: 3,
        type: 'meal',
        title: 'Spaguetti Gambe',
        description: 'Massa fresca com camarões e pesto. ',
        img: 'mask-group-2.png',
        price: 79.97,
        ingredients: [
            'camarão',
            'cebola',
            'pesto',
            'pepino',
            'rabanete',
            'tomate'
        ],
        isFav: false,
    },
    {
        id: 4,
        type: 'meal',
        title: 'Spaguetti Gambe',
        description: 'Massa fresca com camarões e pesto. ',
        img: 'mask-group-2.png',
        price: 79.97,
        ingredients: [
            'camarão',
            'cebola',
            'pesto',
            'pepino',
            'rabanete',
            'tomate'
        ],
        isFav: false,
    },
    {
        id: 5,
        type: 'meal',
        title: 'Torradas de Parma',
        description: 'Presunto de parma e rúcula em um pão com fermentação natural.',
        img: 'mask-group-1.png',
        price: 25.97,
        ingredients: [
            'alface',
            'cebola',
            'pão naan',
            'pepino',
            'rabanete',
            'tomate'
        ],
        isFav: false,
    },
    {
        id: 6,
        type: 'meal',
        title: 'Torradas de Parma',
        description: 'Presunto de parma e rúcula em um pão com fermentação natural.',
        img: 'mask-group-1.png',
        price: 25.97,
        ingredients: [
            'alface',
            'cebola',
            'pão naan',
            'pepino',
            'rabanete',
            'tomate'
        ],
        isFav: false,
    },
    {
        id: 7,
        type: 'meal',
        title: 'Torradas de Parma',
        description: 'Presunto de parma e rúcula em um pão com fermentação natural.',
        img: 'mask-group-1.png',
        price: 25.97,
        ingredients: [
            'alface',
            'cebola',
            'pão naan',
            'pepino',
            'rabanete',
            'tomate'
        ],
        isFav: false,
    },
]